language: python
python:
  - "3.9"

services:
  - docker

before_install:
- docker build . -t lasamar/test24i_sampleapp
- docker run -p 8081:8081 -d lasamar/test24i_sampleapp

script:
- python3 quicktest.py

#after_install:
