language: python
python:
  - "3.9"

services:
  - docker

before_install:
  - docker build . -t lasamar/test24i_sampleapp
  - docker run -p 8081:8081 -d lasamar/test24i_sampleapp

script:
  - python3 quicktest.py

after_success:
  - eval $(aws ecr get-login)
  - docker tag lasamar/test24i_sampleapp:latest $DOCKER_REGISTRY_ECR/davide_sampletest:$TRAVIS_COMMIT
  - docker push $DOCKER_REGISTRY_ECR/davide_sampletest:$TRAVIS_COMMIT

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_DEFAULT_REGION
  app: "davide"
  env: "Davide"
  bucket: "24i-build-artifact"
  bucket_path: Davide
  on:
    branch: main